java_library(
    name = "less-core",
    srcs = glob([
        "src/main/**/*.java",
    ]),
    resources = glob([
        "src/main/resources/**",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "@org_apache_commons_commons_lang3//jar",
    ],
)
